---
- hosts: localhost
  tasks:
    - name: find role dirs and files
      find:
        paths: /var/lib/awx/
        recurse: yes
        file_type: file
        patterns: '*listf*'
#        excludes: 'python3.6'
      register: outlist
    - debug: msg="{{ outlist.files }}"
#      with_items: "{{ outlist.files }}"