---
- hosts: localhost
  tasks:
    - name: find role dirs and files
      find:
        paths: /var/lib/awx
        recurse: yes
        file_type: directory
      register: outlist
    - debug: msg="{{ outlist.files }}"
#      with_items: "{{ outlist.files }}"