---
- hosts: localhost
  tasks:
    - name: find role dirs and files
      find:
        paths: /var/lib/awx
        recurse: yes
      register: outlist
    - debug: 
        msg="{{ [item.path] }}"
      with_items: "{{ outlist.files }}"