---
- hosts: ASA
  gather_facts: yes
  user: nmsadmin
  connection: local
  become: yes
  become_method: enable

  tasks:

   - name: show run
     asa_command:
       commands: show run
     register: run
     become: yes
     tags:
       - show_run

   - debug:
       msg: "{{run.stdout[0]}}"
     tags:
       - show_run