---
- hosts: ASA
  gather_facts: yes
  user: nmsadmin
  connection: local
  become: yes
  become_method: enable
  vars:
    vault_secret: tst2/data/cisco
    vault_token: s.s67Xlia8FpDTPOiAKBg4LZRx
    vault_url: http://10.80.23.81:8200
    vault_options: "secret={{ vault_secret }} token={{ vault_token }} url={{ vault_url }}"

    creds: "{{ lookup('hashi_vault', vault_options).data }}"

    ansible_user: "{{ creds.username }}"
    ansible_password: "{{ creds.password }}"
    ansible_enable:  "{{ creds.enable }}"

  tasks:
      - name: show run
        asa_command:
          commands: show run
        register: sh_run
        become: yes
      
      - name: show ver
        debug: msg="{{ sh_run.stdout }}"