---
- hosts: 10.70.1.4
  gather_facts: yes
  connection: local 
  become: yes
  become_method: enable

  tasks:

    - name Get nxos facts
      nxos_facts:
        gather_subset: all
    - name: Gather only the config and default facts
      nxos_facts:
        gather_subset:
        - config