- name: Gather credentials
  hosts: all
  gather_facts: no
  no_log: true
  vars:
     ansible_use_persistent_connections: true
  
  tasks:
    - name: Set role_id for Vault
      set_fact:
        role_id: "39c3778e-5459-de1f-92b8-b9ac46a6145a"

    - name: Get unwrapper token and wrapped secret_id token
      uri:
        url: https://vault-secret-service-dev.osapps.eagleaccess.com/api/v1/secret/approle/cmp2  
        method: PUT
        return_content: yes
      register: tokens
      delegate_to: localhost

    - name: Get secret_id
      vss_unwrap_secret_id:
        role_id: "{{ role_id }}"
        wrapped_token: "{{ tokens.json.token }}"
      register: secret_id   
      delegate_to: localhost
    
    - name: Get credentials for Test
      vss_get_secret:
        role_id: "{{ role_id }}"
        secret_id: "{{ secret_id.secret_id }}"
        path: "shared/"
      register: test_credentials
      delegate_to: localhost