---
- hosts: 10.148.254.12
  gather_facts: yes
  connection: local 
  become: yes
  become_method: enable

  tasks:

    - name Get nxos facts
      cisco.nxos.nxos_facts:
        gather_subset: all
    - name: Gather only the config and default facts
      cisco.nxos.nxos_facts:
        gather_subset:
        - config