---
- hosts: 10.148.254.23
  gather_facts: no
  user: steve
  connection: local 
  become: yes
  become_method: enable

  tasks:

   - name: Gather all legacy facts 
     asa_facts:
       gather_subset: all