---
- hosts: NXOS
  gather_facts: yes
  connection: network_cli
  become: yes
  become_method: enable

  vault_secret: tst2/data/cisco
  vault_token: s.s67Xlia8FpDTPOiAKBg4LZRx
  vault_url: http://10.80.23.81:8200
  vault_options: "secret={{ vault_secret }} token={{ vault_token }} url={{ vault_url }}"

  creds: "{{ lookup('hashi_vault', vault_options).data }}"

  ansible_user: "{{ creds.username }}"
  ansible_password: "{{ creds.password }}"

  tasks:
    - name: Get nxos facts
      nxos_command:
        commands: show ver
        timeout: 30
      register: ver_cmd

    - name: show ver
      debug: msg="{{ ver_out.stdout }}"