- hosts: 10.70.12.13
  connection: local


  tasks:
    - name: Check to see if device is ready
      paloaltonetworks.panos.panos_op:
        cmd: 'show chassis-ready'
      changed_when: false
      register: result
      until: result is not failed and (result.stdout | from_json).response.result == 'yes'
      retries: 50
      delay: 30