- hosts: 10.70.12.13
  connection: local

#  vars:
#    device:
#      ip_address: 10.70.12.13
#      username: '{{ username | default(omit) }}'
#      password: '{{ password | default(omit) }}'
#      api_key: '{{ api_key | default(omit) }}'


  tasks:
    - name: Check to see if device is ready
      panos_check:
        cmd: 'show chassis-ready'
#      changed_when: false
      register: result
      until: not result|failed
      retries: 50
      delay: 30