---
- hosts: PaloAlto
#- hosts: 10.148.254.20
  connection: local
  vars:
    - creds: "{{ lookup('hashi_vault', 'secret=tst2/data/cisco token=s.s67Xlia8FpDTPOiAKBg4LZRx url=http://10.80.23.81:8200') }}"

  tasks:
    - name: set Cisco creds
      set_fact:
        cisco: "{{ creds['data'] }}"

    - name: list of interfaces
      panos_op:
        ip_address: "{{ inventory_hostname }}"
        username: "{{ cisco['username'] }}"
        password: "{{ cisco['password'] }}"
        cmd: 'show interface all'
      register: int_result
    - debug: msg="{{ int_result.stdout }}"
#        var: int_result
#        verbosity: 2