---
- hosts: 10.148.254.20
  connection: local

#  roles:
#    - role: paloaltonetworks

  tasks:
    - name: list of interfaces
      panos_op:
        ip_address: 10.148.254.20
        username: "nmsadmin"
        password: "NiS01801"
        cmd: 'show interface all'
      register: int_result
    - debug: msg="{{ int_result.stdout }}"

#        var: int_result
#        verbosity: 2
